const assert = require('assert');
const fs = require('fs');
const path = require('path');
const root = path.join(__dirname, '..');
const html = fs.readFileSync(path.join(root, 'index.html'), 'utf8');
const css = fs.readFileSync(path.join(root, 'style.css'), 'utf8');
const app = fs.readFileSync(path.join(root, 'app.js'), 'utf8');
const brandLogoPath = path.join(root, 'assets', 'brand', 'lexbnb-logo.svg');
const brandMarkPath = path.join(root, 'assets', 'brand', 'lexbnb-mark.svg');
const favicon32Path = path.join(root, 'assets', 'brand', 'favicon-32.png');
const appleTouchPath = path.join(root, 'assets', 'brand', 'apple-touch-icon.png');
const emailTemplatePath = path.join(root, 'supabase', 'email_templates', 'lexbnb-auth.html');
assert(html.includes('id="mobileQuickBookingBtn"') && html.includes('id="quickBookingModal"'), 'Mobil hızlı rezervasyon kapısı eksik');
assert(app.includes('function saveQuickBooking') && app.includes("canWriteSalesRole(activeTenant?.role)"), 'Hızlı rezervasyon satış rolü kapısından geçmeli');
assert(css.includes('.mobile-quick-booking') && css.includes('overflow-x: visible'), '390 px mobil eylem ve kart stili eksik');
assert(css.includes('.side-panel') && css.includes('width: 100vw'), 'SidePanel mobilde tam ekran olmalı');
assert(html.includes('id="dynamicFavicon"') && html.includes('id="loginBusinessLogo"'), 'Logo favicon ve giriş yüzeyine bağlanmalı');
assert(html.includes('assets/brand/lexbnb-mark.svg') && html.includes('assets/brand/lexbnb-logo-dark.svg'), 'Onaylanan Lexbnb marka varlıkları site, favicon ve giriş ekranına bağlanmalı');
assert(fs.existsSync(brandLogoPath) && fs.existsSync(brandMarkPath), 'SVG logo ve marka işareti seti eksik');
assert(fs.existsSync(favicon32Path) && fs.existsSync(appleTouchPath), 'PNG favicon seti eksik');
assert(html.includes('assets/brand/favicon-32.png') && html.includes('assets/brand/apple-touch-icon.png'), 'PNG favicon seti belgeye bağlanmalı');
assert(app.includes("logoUrl: appData.businessLogoUrl || 'assets/brand/lexbnb-logo.svg'"), 'Raporlar kiracı logosu yoksa Lexbnb logosuna dönmeli');
assert(fs.existsSync(emailTemplatePath), 'Markalı e-posta şablonu eksik');
const emailTemplate = fs.readFileSync(emailTemplatePath, 'utf8');
assert(emailTemplate.includes('https://lexbnb.space/assets/brand/lexbnb-logo-email.png'), 'E-posta şablonu yayınlanan Lexbnb logosuna bağlı olmalı');
console.log('[PASS] A5-G4 mobil kartlar, tam ekran panel, hızlı rezervasyon ve logo yüzeyleri');
