const assert = require('assert'); const service = require('./marketing_economics_worker_service');
let total = 0; let passed = 0; async function test(name, fn) { total += 1; try { await fn(); passed += 1; console.log(`[PASS] ${name}`); } catch (error) { console.error(`[FAIL] ${name}\n       ${error.stack || error.message}`); } }
const scope = { tenant_id: 'T1', id: 'P1' };
const bookings = Array.from({ length: 10 }, (_, index) => ({ id: `B${index}`, property_id: 'P1', channel: index === 0 ? 'DIRECT' : 'AIRBNB', check_in: `2026-08-${String(index + 1).padStart(2, '0')}`, check_out: `2026-08-${String(index + 2).padStart(2, '0')}`, gross_amount: 10000, ota_commission: index === 0 ? 0 : 2000, status: 'CONFIRMED' }));
function repo(overrides = {}) { const findings = []; return { findings, async loadPropertyScopes() { return [scope]; }, async loadBenchmark() { return { max_distribution_cost_percent: 15, minimum_direct_reservation_share_percent: 20 }; }, async loadBookings() { return bookings; }, async persistFinding(draft) { findings.push(draft); return 'F1'; }, ...overrides }; }
(async () => {
  await test('Worker computes and persists benchmark-backed property findings', async () => { const repository = repo(); const result = await service.runEconomicsFindings(repository, { asOfDate: '2026-09-01' }); assert.strictEqual(result.persisted, 2); assert.deepStrictEqual(repository.findings.map(row => row.findingCode), ['DISTRIBUTION_COST_ABOVE_REFERENCE', 'DIRECT_SHARE_BELOW_REFERENCE']); });
  await test('Missing benchmark is explicitly skipped without loading bookings', async () => { let loaded = false; const repository = repo({ async loadBenchmark() { return null; }, async loadBookings() { loaded = true; return []; } }); const result = await service.runEconomicsFindings(repository, { asOfDate: '2026-09-01' }); assert.strictEqual(result.skipped[0].reason, 'NO_BENCHMARK'); assert.strictEqual(loaded, false); });
  await test('One property failure does not abort other properties', async () => { const repository = repo({ async loadPropertyScopes() { return [scope, { tenant_id: 'T1', id: 'P2' }]; }, async loadBookings(t, p) { if (p === 'P2') throw new Error('read failed'); return bookings; } }); const result = await service.runEconomicsFindings(repository, { asOfDate: '2026-09-01' }); assert.strictEqual(result.status, 'PARTIAL'); assert.strictEqual(result.errors.length, 1); assert.strictEqual(result.persisted, 2); });
  console.log(`\nTEST SUMMARY: ${passed} / ${total} TESTS PASSED`); if (passed !== total) process.exit(1);
})();
