const assert = require('assert'); const fs = require('fs'); const path = require('path'); const service = require('./marketing_cover_change_service');
const TENANT = '11111111-1111-4111-8111-111111111111'; const PROPERTY = '22222222-2222-4222-8222-222222222222'; const LISTING = '33333333-3333-4333-8333-333333333333'; const OLD = '44444444-4444-4444-8444-444444444444'; const NEW = '55555555-5555-4555-8555-555555555555'; const EXPERIMENT = '66666666-6666-4666-8666-666666666666';
let total = 0; let passed = 0; async function test(name, fn) { total += 1; try { await fn(); passed += 1; console.log(`[PASS] ${name}`); } catch (error) { console.error(`[FAIL] ${name}\n       ${error.stack || error.message}`); } }
const valid = { tenantId: TENANT, propertyId: PROPERTY, channelListingId: LISTING, expectedOldMediaId: OLD, newMediaId: NEW };
(async () => {
  await test('Current cover selection is listing-scoped and fails on inconsistent duplicates', () => { const rows = [{ channel_listing_id: LISTING, media_id: OLD, is_active: true, is_cover: true }, { channel_listing_id: 'other', media_id: NEW, is_active: true, is_cover: true }]; assert.strictEqual(service.currentCover(rows, LISTING).media_id, OLD); assert.throws(() => service.currentCover([...rows, rows[0]], LISTING), /MULTIPLE/); });
  await test('Stale or identical identifiers are rejected before mutation', () => { assert.throws(() => service.validate({ ...valid, expectedOldMediaId: NEW }), /DISTINCT/); assert.throws(() => service.validate({ ...valid, newMediaId: 'bad' }), /VALID_NEW_MEDIA/); });
  await test('One guarded RPC returns an explicitly observational result', async () => { const calls = []; const client = { rpc: async (name, args) => { calls.push({ name, args }); return { data: { oldMediaId: OLD, newMediaId: NEW, experimentId: EXPERIMENT, changeDate: '2026-09-13', idempotentReplay: false, externalPublishStatus: 'NOT_ATTEMPTED' } }; } }; const result = await service.changeCoverAndMeasure(client, valid); assert.strictEqual(calls[0].name, 'change_channel_cover_and_measure'); assert.strictEqual(calls[0].args.p_expected_old_media_id, OLD); assert.strictEqual(result.causalClaim, false); assert.strictEqual(result.externalPublishStatus, 'NOT_ATTEMPTED'); });
  await test('Database errors and malformed results remain visible', async () => { await assert.rejects(() => service.changeCoverAndMeasure({ rpc: async () => ({ error: new Error('stale') }) }, valid), /stale/); await assert.rejects(() => service.changeCoverAndMeasure({ rpc: async () => ({ data: {} }) }, valid), /INVALID_COVER_CHANGE_RESULT/); });
  await test('Schema uses locked compare-and-swap, one transaction and no external publication', () => { const sql = fs.readFileSync(path.join(__dirname, '..', 'supabase', 'migration_phase17_cover_change.sql'), 'utf8'); assert.match(sql, /v_current_media_id IS DISTINCT FROM p_expected_old_media_id[\s\S]+STALE_EXPECTED_COVER/i); assert.match(sql, /FOR UPDATE OF placement/i); assert.match(sql, /NEW_MEDIA_PLACEMENT_CHANGED_CONCURRENTLY/i); assert.match(sql, /request_listing_change_evaluation/i); assert.match(sql, /v_change_date - 14[\s\S]+v_change_date \+ 14/i); assert.match(sql, /externalPublishStatus', 'NOT_ATTEMPTED/i); assert.match(sql, /COALESCE\(public\.get_tenant_role\(p_tenant_id\), ''\) NOT IN \('owner', 'admin', 'manager'\)/i); assert.doesNotMatch(sql, /http|fetch|webhook/i); });
  console.log(`\nTEST SUMMARY: ${passed} / ${total} TESTS PASSED`); if (passed !== total) process.exit(1);
})();
